# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 name: rancher-agent


variables:
  GitVersion.SemVer: ''



steps: 
- task: gitversion/setup@1
  inputs:
    versionSpec: '5.12.0'
    updateAssemblyInfo: true
- script: |
    dotnet-gitversion /showConfig
    set
    cd cicd
    ls -latR
    echo ${GitVersion.Semver}
  displayName: 'Show Gitversion Config'
- script: |
    cd cicd
    ./build.sh 3.8.0-buildah
  displayName: 'Build with buildah'
