# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 name: rancher-agent


variables:
  GitVersion.SemVer: ''



steps: 
- task: GitVersion@5 
  inputs: 
     runtime: 'core' 
     configFilePath: 'GitVersion.yml' # Optional: Path to GitVersion configuration file 
     updateAssemblyInfo: true # Optional: Automatically update the AssemblyInfo files with version information
- script: |
    dotnet-gitversion /showConfig
    set
    cd cicd
    ls -latR
  displayName: 'Show Gitversion Config'
- script: |
    cd cicd
    ./build.sh 3.8.0-buildah
  displayName: 'Build with buildah'
