{{- if .Values.secretproviderclass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
    name: {{ include "javadaprchart.fullname" .}}-spc
spec:
    parameters:
        cloudName: AzurePublicCloud
        keyvaultName: daprbc2024kv
        objects: |
            array:
            {{- range .Values.secretproviderclass.secrets }}
            - |
              objectName: {{ tpl .secret $ }}
              objectType: {{ tpl .type $ }}   
              objectVersion: ""
            {{- end }}  
        resourcegroup: dapr-components
        subscriptionId: 2bf1b36d-cb70-413c-8fd3-b275758a0145
        tenantId: d3dd5ac6-2c23-4080-a3fc-a27625fd456c
        clientID: {{ .Values.workloadidentity.clientid }}   
        usePodIdentity: "false"
    provider: azure
{{- end }}