{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "javadaprchart.serviceAccountName" . }}
  labels:
    {{- include "javadaprchart.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.workloadidentity.enabled }}
    azure.workload.identity/client-id: {{ .Values.workloadidentity.clientid }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
